import { mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { Logger } from "pino";
import YAML from "yaml";
import type { AgentDefinition } from "./agent-definitions.js";
import { AGENTS_DIR } from "./inspect-workspace-contract.js";
import { ifMissing } from "./optional-file.js";
import { syncOwnedLinks } from "./owned-links.js";
import { type Vendor, isVendor, resolveVendorConfigDir } from "./vendor-config-dir.js";

interface AgentBridge {
  /** The vendor's user-level agents directory, inside its config dir. */
  dirName: string;
  extension: string;
  /** The vendor's own file for a definition, or null to link the source file itself. */
  render: ((agent: AgentDefinition) => string) | null;
}

const AGENT_BRIDGES: Readonly<Record<Vendor, AgentBridge>> = {
  // Claude Code reads the source format and ignores the `codex:` block.
  claude: { dirName: "agents", extension: ".md", render: null },
  codex: { dirName: "agents", extension: ".toml", render: renderCodexRole },
  opencode: { dirName: "agent", extension: ".md", render: renderOpenCodeAgent },
};

/**
 * Links each definition into the user-level agents directory of the vendor that `baseProviderId`
 * launches. Claude gets the source file. Codex and OpenCode get a file generated into
 * `~/.agents/.generated/agents/<vendor>`. A vendor's own file with the same name blocks the link.
 * Failures are logged, so a launch never fails here.
 */
export async function bridgeAgentDefinitions(params: {
  home: string;
  baseProviderId: string;
  /** The env the provider process is launched with, for `CLAUDE_CONFIG_DIR` and `CODEX_HOME`. */
  env: NodeJS.ProcessEnv;
  agents: readonly AgentDefinition[];
  logger: Logger;
}): Promise<void> {
  const { home, baseProviderId: vendor, agents, logger } = params;
  if (!isVendor(vendor)) return;
  const { dirName, extension, render } = AGENT_BRIDGES[vendor];
  try {
    let ownedRoot = join(home, AGENTS_DIR, "agents");
    let wanted = new Map(agents.map((agent) => [agent.name + extension, agent.path]));
    if (render) {
      ownedRoot = join(home, AGENTS_DIR, ".generated", "agents", vendor);
      const files = new Map(agents.map((agent) => [agent.name + extension, render(agent)]));
      wanted = await writeGeneratedFiles(ownedRoot, files);
    }
    await syncOwnedLinks({
      dir: join(resolveVendorConfigDir(vendor, params), dirName),
      ownedRoot,
      wanted,
      logger,
    });
  } catch (error) {
    logger.warn({ err: error }, `Failed to bridge ~/.agents/agents into ${vendor}`);
  }
}

/** Makes `dir` hold exactly `files`, by name, and returns each file's path. */
async function writeGeneratedFiles(
  dir: string,
  files: ReadonlyMap<string, string>,
): Promise<Map<string, string>> {
  // syncOwnedLinks keeps an owned link while its target exists, so the file of a removed
  // definition goes first, and the link sync then removes its dangling link.
  for (const fileName of await readdir(dir).catch(ifMissing([]))) {
    if (!files.has(fileName)) await rm(join(dir, fileName), { recursive: true, force: true });
  }
  const paths = new Map<string, string>();
  for (const [fileName, content] of files) {
    const path = join(dir, fileName);
    if ((await readFile(path, "utf8").catch(ifMissing(null))) !== content) {
      await mkdir(dir, { recursive: true });
      await writeFile(path, content);
    }
    paths.set(fileName, path);
  }
  return paths;
}

// Codex 0.159 requires `name`, `description` and `developer_instructions`. The `codex:` keys are
// ordinary Codex config keys, such as `model` or `sandbox_mode`.
function renderCodexRole(agent: AgentDefinition): string {
  const codexKeys = Object.entries(agent.codex).map(
    ([key, value]) => `${key} = ${typeof value === "string" ? tomlString(value) : String(value)}`,
  );
  return [
    `# Generated by Paseo from ${agent.path}. Edit that file instead.`,
    `name = ${tomlString(agent.name)}`,
    `description = ${tomlString(agent.description)}`,
    ...codexKeys,
    `developer_instructions = ${tomlString(agent.prompt)}`,
    "",
  ].join("\n");
}

// A JSON string literal is a TOML basic string with the same escapes, except that TOML also
// requires DEL (U+007F) to be escaped.
function tomlString(value: string): string {
  return JSON.stringify(value).replaceAll("\u007f", "\\u007f");
}

// One value that OpenCode reads differently, such as a Claude `tools` list or color name, makes it
// reject its whole config, so only the description is mapped. `mode: subagent` keeps the agent out
// of the primary agents that Paseo offers as modes.
function renderOpenCodeAgent(agent: AgentDefinition): string {
  const frontmatter = YAML.stringify(
    { description: agent.description, mode: "subagent" },
    { lineWidth: 0 },
  );
  return `---\n${frontmatter}---\n${agent.prompt}\n`;
}
